export const STRINGS = {
    en: { mo:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'], tr:n=>n===1?'1 track':`${n} tracks`, cr:'created', ed:'edited', nb:'listening from nearby', fa:n=>`listening from ${n.toLocaleString()} miles away`, au:'audio via YouTube', auf:h=>`audio via ${h}`, mi:true, pl:'Playlist', pc:'Player controls', pp:'Playback position', play:'Play', pause:'Pause', by:(t,a)=>`${t} by ${a}`, np:(t,a)=>`Now playing: ${t} by ${a}`, pe:'Playlist ended.', of:(c,d)=>`${c} of ${d}`, lh:'how far away are you?', lp:'computed on your device · never sent anywhere', ll:'locating…', offline:'offline', buf:'weak connection', vz:'Visualization', lb:'tape library', sh:'Share tape', bk:t=>`back to ${t}`, rs:t=>`resume from ${t}` },
    es: { mo:['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'], tr:n=>n===1?'1 pista':`${n} pistas`, cr:'creado', ed:'editado', nb:'escuchando desde cerca', fa:n=>`escuchando desde ${n.toLocaleString()} km`, au:'audio vía YouTube', auf:h=>`audio vía ${h}`, mi:false, pl:'Lista de reproducción', pc:'Controles del reproductor', pp:'Posición de reproducción', play:'Reproducir', pause:'Pausar', by:(t,a)=>`${t} de ${a}`, np:(t,a)=>`Reproduciendo: ${t} de ${a}`, pe:'Lista de reproducción finalizada.', of:(c,d)=>`${c} de ${d}`, lh:'¿a qué distancia estás?', lp:'calculado en tu dispositivo · nunca se envía a ningún sitio', ll:'ubicando…', offline:'sin conexión', buf:'conexión débil', vz:'Visualización', lb:'biblioteca de cintas', sh:'Compartir cinta', bk:t=>`volver a ${t}`, rs:t=>`reanudar desde ${t}` },
    it: { mo:['gen','feb','mar','apr','mag','giu','lug','ago','set','ott','nov','dic'], tr:n=>n===1?'1 brano':`${n} brani`, cr:'creato', ed:'modificato', nb:'in ascolto da vicino', fa:n=>`in ascolto a ${n.toLocaleString()} km`, au:'audio via YouTube', auf:h=>`audio via ${h}`, mi:false, pl:'Playlist', pc:'Controlli del lettore', pp:'Posizione di riproduzione', play:'Riproduci', pause:'Pausa', by:(t,a)=>`${t} di ${a}`, np:(t,a)=>`In riproduzione: ${t} di ${a}`, pe:'Playlist terminata.', of:(c,d)=>`${c} di ${d}`, lh:'quanto sei lontano?', lp:'calcolato sul tuo dispositivo · non viene mai inviato', ll:'localizzazione…', offline:'non in linea', buf:'connessione debole', vz:'Visualizzazione', lb:'raccolta di nastri', sh:'Condividi il nastro', bk:t=>`torna a ${t}`, rs:t=>`riprendi da ${t}` },
    de: { mo:['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'], tr:n=>`${n} Titel`, cr:'erstellt', ed:'bearbeitet', nb:'von hier in der Nähe', fa:n=>`aus ${n.toLocaleString()} km`, au:'Musik via YouTube', auf:h=>`Musik via ${h}`, mi:false, pl:'Wiedergabeliste', pc:'Player-Steuerelemente', pp:'Wiedergabeposition', play:'Abspielen', pause:'Pausieren', by:(t,a)=>`${t} von ${a}`, np:(t,a)=>`Jetzt: ${t} von ${a}`, pe:'Wiedergabeliste beendet.', of:(c,d)=>`${c} von ${d}`, lh:'wie weit bist du entfernt?', lp:'auf deinem Gerät berechnet · wird nirgendwohin gesendet', ll:'wird lokalisiert…', offline:'offline', buf:'schwache Verbindung', vz:'Visualisierung', lb:'Kassettenbibliothek', sh:'Kassette teilen', bk:t=>`zurück zu ${t}`, rs:t=>`fortsetzen ab ${t}` },
    fr: { mo:['jan','fév','mar','avr','mai','jun','jul','aoû','sep','oct','nov','déc'], tr:n=>n===1?'1 titre':`${n} titres`, cr:'créé', ed:'modifié', nb:"à l'écoute depuis tout près", fa:n=>`à l'écoute depuis ${n.toLocaleString()} km`, au:'audio via YouTube', auf:h=>`audio via ${h}`, mi:false, pl:'Liste de lecture', pc:'Commandes du lecteur', pp:'Position de lecture', play:'Lecture', pause:'Pause', by:(t,a)=>`${t} par ${a}`, np:(t,a)=>`En lecture : ${t} par ${a}`, pe:'Liste de lecture terminée.', of:(c,d)=>`${c} sur ${d}`, lh:'à quelle distance es-tu ?', lp:'calculé sur ton appareil · jamais envoyé', ll:'localisation…', offline:'hors ligne', buf:'connexion faible', vz:'Visualisation', lb:'bibliothèque de cassettes', sh:'Partager la cassette', bk:t=>`retour à ${t}`, rs:t=>`reprendre à ${t}` },
    zh: { mo:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tr:n=>`${n} 首`, cr:'创建', ed:'编辑', nb:'正在附近收听', fa:n=>`正在从 ${n.toLocaleString()} 公里外收听`, au:'音频来自 YouTube', auf:h=>`音频来自 ${h}`, mi:false, pl:'播放列表', pc:'播放器控件', pp:'播放位置', play:'播放', pause:'暂停', by:(t,a)=>`${a} - ${t}`, np:(t,a)=>`正在播放：${a} - ${t}`, pe:'播放列表已结束。', of:(c,d)=>`${c} / ${d}`, lh:'你离这里多远？', lp:'在你的设备上计算 · 绝不发送到任何地方', ll:'定位中…', offline:'离线', buf:'网络信号弱', vz:'可视化效果', lb:'磁带库', sh:'分享磁带', bk:t=>`返回 ${t}`, rs:t=>`从 ${t} 继续播放` },
    ko: { mo:['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'], tr:n=>`${n}곡`, cr:'제작', ed:'수정', nb:'근처에서 듣는 중', fa:n=>`${n.toLocaleString()}km 떨어진 곳에서 듣는 중`, au:'YouTube 음원', auf:h=>`${h} 음원`, mi:false, pl:'재생목록', pc:'플레이어 컨트롤', pp:'재생 위치', play:'재생', pause:'일시정지', by:(t,a)=>`${a} - ${t}`, np:(t,a)=>`재생 중: ${a} - ${t}`, pe:'재생목록이 종료되었습니다.', of:(c,d)=>`${c} / ${d}`, lh:'얼마나 멀리 있나요?', lp:'기기에서 계산됨 · 어디에도 전송되지 않음', ll:'위치 확인 중…', offline:'오프라인', buf:'연결 불안정', vz:'시각화', lb:'테이프 라이브러리', sh:'테이프 공유', bk:t=>`${t}(으)로 돌아가기`, rs:t=>`${t}부터 이어 듣기` },
    ja: { mo:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tr:n=>`${n}曲`, cr:'作成', ed:'更新', nb:'近くで再生中', fa:n=>`${n.toLocaleString()}km 離れた場所で再生中`, au:'YouTube より配信', auf:h=>`${h} より配信`, mi:false, pl:'プレイリスト', pc:'プレーヤーコントロール', pp:'再生位置', play:'再生', pause:'一時停止', by:(t,a)=>`${a} - ${t}`, np:(t,a)=>`再生中：${a} - ${t}`, pe:'プレイリストが終了しました。', of:(c,d)=>`${c} / ${d}`, lh:'どれくらい離れていますか？', lp:'端末内で計算 · どこにも送信されません', ll:'位置を取得中…', offline:'オフライン', buf:'接続が不安定', vz:'ビジュアライザー', lb:'テープライブラリ', sh:'テープを共有', bk:t=>`${t} に戻る`, rs:t=>`${t} から再開` },
    ru: { mo:['янв','фев','мар','апр','май','июн','июл','авг','сен','окт','ноя','дек'], tr:n=>{const m=n%10,c=n%100;return m===1&&c!==11?`${n} трек`:m>=2&&m<=4&&(c<10||c>=20)?`${n} трека`:`${n} треков`;}, cr:'создан', ed:'изменён', nb:'слушаю рядом', fa:n=>`слушаю в ${n.toLocaleString()} км`, au:'аудио с YouTube', auf:h=>`аудио с ${h}`, mi:false, pl:'Плейлист', pc:'Элементы управления', pp:'Позиция воспроизведения', play:'Воспроизвести', pause:'Пауза', by:(t,a)=>`${t} — ${a}`, np:(t,a)=>`Сейчас играет: ${t} — ${a}`, pe:'Плейлист завершён.', of:(c,d)=>`${c} из ${d}`, lh:'как далеко вы?', lp:'вычисляется на вашем устройстве · никуда не отправляется', ll:'определение…', offline:'нет сети', buf:'слабое соединение', vz:'Визуализация', lb:'библиотека кассет', sh:'Поделиться кассетой', bk:t=>`назад к ${t}`, rs:t=>`продолжить с ${t}` },
    hi: { mo:['जन','फ़र','मार','अप्र','मई','जून','जुल','अग','सित','अक्टू','नव','दिस'], tr:n=>`${n} ट्रैक`, cr:'बनाया', ed:'संपादित', nb:'पास से सुन रहे हैं', fa:n=>`${n.toLocaleString()} किमी दूर से सुन रहे हैं`, au:'YouTube से ऑडियो', auf:h=>`${h} से ऑडियो`, mi:false, pl:'प्लेलिस्ट', pc:'प्लेयर नियंत्रण', pp:'प्लेबैक स्थिति', play:'चलाएं', pause:'रोकें', by:(t,a)=>`${t} - ${a}`, np:(t,a)=>`अभी चल रहा है: ${t} - ${a}`, pe:'प्लेलिस्ट समाप्त हुई।', of:(c,d)=>`${c} में से ${d}`, lh:'आप कितनी दूर हैं?', lp:'आपके डिवाइस पर गणना · कहीं नहीं भेजा जाता', ll:'स्थान खोज रहे हैं…', offline:'ऑफ़लाइन', buf:'कमज़ोर कनेक्शन', vz:'विज़ुअलाइज़ेशन', lb:'टेप लाइब्रेरी', sh:'टेप साझा करें', bk:t=>`${t} पर वापस जाएं`, rs:t=>`${t} से फिर शुरू करें` },
    mr: { mo:['जाने','फेब्रु','मार्च','एप्रि','मे','जून','जुलै','ऑग','सप्टें','ऑक्टो','नोव्हें','डिसें'], tr:n=>`${n} ट्रॅक`, cr:'बनवले', ed:'संपादित', nb:'जवळून ऐकत आहात', fa:n=>`${n.toLocaleString()} किमी दूरून ऐकत आहात`, au:'YouTube वरून ऑडिओ', auf:h=>`${h} वरून ऑडिओ`, mi:false, pl:'प्लेलिस्ट', pc:'प्लेयर नियंत्रणे', pp:'प्लेबॅक स्थान', play:'प्ले करा', pause:'थांबवा', by:(t,a)=>`${t} - ${a}`, np:(t,a)=>`आता वाजत आहे: ${t} - ${a}`, pe:'प्लेलिस्ट संपली.', of:(c,d)=>`${c} / ${d}`, lh:'तुम्ही किती दूर आहात?', lp:'तुमच्या डिव्हाइसवर मोजले · कुठेही पाठवले जात नाही', ll:'स्थान शोधत आहे…', offline:'ऑफलाइन', buf:'कमकुवत कनेक्शन', vz:'व्हिज्युअलायझेशन', lb:'टेप लायब्ररी', sh:'टेप शेअर करा', bk:t=>`${t} वर परत जा`, rs:t=>`${t} पासून पुन्हा सुरू करा` },
  };

export const lang = ((typeof navigator !== 'undefined' ? navigator.language : null) || 'en').split('-')[0].toLowerCase();
export const L = STRINGS[lang] || STRINGS.en;

export function fmtDate(iso) {
  if (!iso) return '';
  const [y, m, d] = iso.split('-');
  if (!y || !m || !d || isNaN(+m) || isNaN(+d) || +m < 1 || +m > 12) return '';
  const dd = String(+d).padStart(2, '0');
  if (lang === 'zh' || lang === 'ja') return `${y}年${+m}月${dd}日`;
  if (lang === 'ko') return `${y}년 ${+m}월 ${dd}일`;
  return `${dd} ${L.mo[+m - 1]} ${y}`;
}
