export const STRINGS = {
    en: { mo:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'], tr:n=>n===1?'1 track':`${n} tracks`, cr:'created', ed:'edited', nb:'listening from nearby', fa:n=>`listening from ${n.toLocaleString()} miles away`, au:'audio via YouTube', mi:true, pl:'Playlist', pc:'Player controls', pp:'Playback position', play:'Play', pause:'Pause', by:(t,a)=>`${t} by ${a}`, np:(t,a)=>`Now playing: ${t} by ${a}`, pe:'Playlist ended.', of:(c,d)=>`${c} of ${d}`, pi:'Enable tilt peek' },
    es: { mo:['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'], tr:n=>n===1?'1 pista':`${n} pistas`, cr:'creado', ed:'editado', nb:'escuchando desde cerca', fa:n=>`escuchando desde ${n.toLocaleString()} km`, au:'audio vía YouTube', mi:false, pl:'Lista de reproducción', pc:'Controles del reproductor', pp:'Posición de reproducción', play:'Reproducir', pause:'Pausar', by:(t,a)=>`${t} de ${a}`, np:(t,a)=>`Reproduciendo: ${t} de ${a}`, pe:'Lista de reproducción finalizada.', of:(c,d)=>`${c} de ${d}`, pi:'Activar vista con inclinación' },
    it: { mo:['gen','feb','mar','apr','mag','giu','lug','ago','set','ott','nov','dic'], tr:n=>n===1?'1 brano':`${n} brani`, cr:'creato', ed:'modificato', nb:'in ascolto da vicino', fa:n=>`in ascolto a ${n.toLocaleString()} km`, au:'audio via YouTube', mi:false, pl:'Playlist', pc:'Controlli del lettore', pp:'Posizione di riproduzione', play:'Riproduci', pause:'Pausa', by:(t,a)=>`${t} di ${a}`, np:(t,a)=>`In riproduzione: ${t} di ${a}`, pe:'Playlist terminata.', of:(c,d)=>`${c} di ${d}`, pi:'Attiva anteprima inclinazione' },
    de: { mo:['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'], tr:n=>`${n} Titel`, cr:'erstellt', ed:'bearbeitet', nb:'von hier in der Nähe', fa:n=>`aus ${n.toLocaleString()} km`, au:'Musik via YouTube', mi:false, pl:'Wiedergabeliste', pc:'Player-Steuerelemente', pp:'Wiedergabeposition', play:'Abspielen', pause:'Pausieren', by:(t,a)=>`${t} von ${a}`, np:(t,a)=>`Jetzt: ${t} von ${a}`, pe:'Wiedergabeliste beendet.', of:(c,d)=>`${c} von ${d}`, pi:'Kippansicht aktivieren' },
    fr: { mo:['jan','fév','mar','avr','mai','jun','jul','aoû','sep','oct','nov','déc'], tr:n=>n===1?'1 titre':`${n} titres`, cr:'créé', ed:'modifié', nb:"à l'écoute depuis tout près", fa:n=>`à l'écoute depuis ${n.toLocaleString()} km`, au:'audio via YouTube', mi:false, pl:'Liste de lecture', pc:'Commandes du lecteur', pp:'Position de lecture', play:'Lecture', pause:'Pause', by:(t,a)=>`${t} par ${a}`, np:(t,a)=>`En lecture : ${t} par ${a}`, pe:'Liste de lecture terminée.', of:(c,d)=>`${c} sur ${d}`, pi:"Activer l'aperçu inclinaison" },
    zh: { mo:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tr:n=>`${n} 首`, cr:'创建', ed:'编辑', nb:'正在附近收听', fa:n=>`正在从 ${n.toLocaleString()} 公里外收听`, au:'音频来自 YouTube', mi:false, pl:'播放列表', pc:'播放器控件', pp:'播放位置', play:'播放', pause:'暂停', by:(t,a)=>`${a} - ${t}`, np:(t,a)=>`正在播放：${a} - ${t}`, pe:'播放列表已结束。', of:(c,d)=>`${c} / ${d}`, pi:'启用倾斜预览' },
    ko: { mo:['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'], tr:n=>`${n}곡`, cr:'제작', ed:'수정', nb:'근처에서 듣는 중', fa:n=>`${n.toLocaleString()}km 떨어진 곳에서 듣는 중`, au:'YouTube 음원', mi:false, pl:'재생목록', pc:'플레이어 컨트롤', pp:'재생 위치', play:'재생', pause:'일시정지', by:(t,a)=>`${a} - ${t}`, np:(t,a)=>`재생 중: ${a} - ${t}`, pe:'재생목록이 종료되었습니다.', of:(c,d)=>`${c} / ${d}`, pi:'기울기 미리보기 활성화' },
    ja: { mo:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tr:n=>`${n}曲`, cr:'作成', ed:'更新', nb:'近くで再生中', fa:n=>`${n.toLocaleString()}km 離れた場所で再生中`, au:'YouTube より配信', mi:false, pl:'プレイリスト', pc:'プレーヤーコントロール', pp:'再生位置', play:'再生', pause:'一時停止', by:(t,a)=>`${a} - ${t}`, np:(t,a)=>`再生中：${a} - ${t}`, pe:'プレイリストが終了しました。', of:(c,d)=>`${c} / ${d}`, pi:'傾き機能を有効にする' },
    ru: { mo:['янв','фев','мар','апр','май','июн','июл','авг','сен','окт','ноя','дек'], tr:n=>{const m=n%10,c=n%100;return m===1&&c!==11?`${n} трек`:m>=2&&m<=4&&(c<10||c>=20)?`${n} трека`:`${n} треков`;}, cr:'создан', ed:'изменён', nb:'слушаю рядом', fa:n=>`слушаю в ${n.toLocaleString()} км`, au:'аудио с YouTube', mi:false, pl:'Плейлист', pc:'Элементы управления', pp:'Позиция воспроизведения', play:'Воспроизвести', pause:'Пауза', by:(t,a)=>`${t} — ${a}`, np:(t,a)=>`Сейчас играет: ${t} — ${a}`, pe:'Плейлист завершён.', of:(c,d)=>`${c} из ${d}`, pi:'Включить просмотр наклоном' },
    hi: { mo:['जन','फ़र','मार','अप्र','मई','जून','जुल','अग','सित','अक्टू','नव','दिस'], tr:n=>`${n} ट्रैक`, cr:'बनाया', ed:'संपादित', nb:'पास से सुन रहे हैं', fa:n=>`${n.toLocaleString()} किमी दूर से सुन रहे हैं`, au:'YouTube से ऑडियो', mi:false, pl:'प्लेलिस्ट', pc:'प्लेयर नियंत्रण', pp:'प्लेबैक स्थिति', play:'चलाएं', pause:'रोकें', by:(t,a)=>`${t} - ${a}`, np:(t,a)=>`अभी चल रहा है: ${t} - ${a}`, pe:'प्लेलिस्ट समाप्त हुई।', of:(c,d)=>`${c} में से ${d}`, pi:'झुकाव पूर्वावलोकन सक्षम करें' },
    mr: { mo:['जाने','फेब्रु','मार्च','एप्रि','मे','जून','जुलै','ऑग','सप्टें','ऑक्टो','नोव्हें','डिसें'], tr:n=>`${n} ट्रॅक`, cr:'बनवले', ed:'संपादित', nb:'जवळून ऐकत आहात', fa:n=>`${n.toLocaleString()} किमी दूरून ऐकत आहात`, au:'YouTube वरून ऑडिओ', mi:false, pl:'प्लेलिस्ट', pc:'प्लेयर नियंत्रणे', pp:'प्लेबॅक स्थान', play:'प्ले करा', pause:'थांबवा', by:(t,a)=>`${t} - ${a}`, np:(t,a)=>`आता वाजत आहे: ${t} - ${a}`, pe:'प्लेलिस्ट संपली.', of:(c,d)=>`${c} / ${d}`, pi:'झुकवणे सक्षम करा' },
  };

export const lang = (navigator.language || 'en').split('-')[0].toLowerCase();
export const L = STRINGS[lang] || STRINGS.en;

export function fmtDate(iso) {
  if (!iso) return '';
  const [y, m, d] = iso.split('-');
  const dd = String(+d).padStart(2, '0');
  if (lang === 'zh' || lang === 'ja') return `${y}年${+m}月${dd}日`;
  if (lang === 'ko') return `${y}년 ${+m}월 ${dd}일`;
  return `${dd} ${L.mo[+m - 1]} ${y}`;
}
